### ISSUE TITLE
No test data

### ISSUE THREAD

**Issue by zhubowen1** [VladimirYugay/gaussian_rasterizer#2]
git clone https://huggingface.co/datasets/voviktyl/gaussian-rasterizer-test-data
Cloning into 'gaussian-rasterizer-test-data'...
fatal: unable to access 'https://huggingface.co/datasets/voviktyl/gaussian-rasterizer-test-data/': Could not resolve host: huggingface.co

Can you share your test_data for debugging ? Thank you

**Comment by VladimirYugay** [comment]
Hey there, 

Hm, it should work. I've just tested it:
![image](https://github.com/VladimirYugay/gaussian_rasterizer/assets/12258972/23e4fcdd-9937-4996-bcde-50ede18693b4)

I can't attach files here since it's larger than 25mb.

Can you try running the command and say what the results are:
`ping huggingface.co`

**Comment by zhubowen1** [comment]
Problem solved. Thank you very much for your work.
